import 'package:get/get.dart';

class Messages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en': {
          Strings.commonOkay.name: 'Okay',
          Strings.commonAlert.name: 'Alert',
          Strings.commonError.name: 'Error',
          Strings.commonFailToGetInformation.name: 'Fail to get information',
          Strings.commonTip.name:
              'Please make sure your device is connected to a valid network '
                  'and this APP is granted location permission. '
                  'Otherwise, this APP will not work properly.',
          Strings.homeTitle.name: 'Amap demo',
          Strings.homeNavigateToLocationButton.name:
              'Navigate to location page',
          Strings.homeNavigateToMapButton.name: 'Navigate to map page',
          Strings.locationTitle.name: 'Location page',
          Strings.locationLocateButton.name: 'Locate',
          Strings.locationStopLocatingButton.name: 'Stop locating',
          Strings.locationTime.name: 'Location time: %s',
          Strings.locationLatitude.name: 'Latitude: %s',
          Strings.locationLongitude.name: 'Longitude: %s',
          Strings.locationAccuracy.name: 'Accuracy: %s',
          Strings.locationCountry.name: 'Country: %s',
          Strings.locationProvince.name: 'Province: %s',
          Strings.locationCity.name: 'City: %s',
          Strings.locationCityCode.name: 'City code: %s',
          Strings.locationDistrict.name: 'District: %s',
          Strings.locationDistrictCode.name: 'District code: %s',
          Strings.locationStreet.name: 'Street: %s',
          Strings.locationStreetNumber.name: 'Street number: %s',
          Strings.locationDescription.name: 'Description: %s',
          Strings.locationTip.name: 'Tap 「Locate」 button to start',
          Strings.mapTitle.name: 'Map page',
          Strings.mapTip.name:
              'Tap to navigate here if you have installed Amap',
          Strings.mapNormalMap.name: 'Normal map',
          Strings.mapSatelliteMap.name: 'Satellite map',
          Strings.mapNightMap.name: 'Night map',
          Strings.mapNavigationMap.name: 'Navigation map',
          Strings.mapBusMap.name: 'Bus map',
          Strings.mapDidNotFindAmap.name: 'Did not find Amap',
        },
        'zh': {
          Strings.commonOkay.name: '好的',
          Strings.commonAlert.name: '警告',
          Strings.commonError.name: '错误',
          Strings.commonFailToGetInformation.name: '获取信息失败',
          Strings.commonTip.name: '请确保设备的网络连接正常并授予应用定位权限, '
              '否则此应用无法正常运行',
          Strings.homeTitle.name: '高德地图示例',
          Strings.homeNavigateToLocationButton.name: '跳转至定位页面',
          Strings.homeNavigateToMapButton.name: '跳转至地图页面',
          Strings.locationTitle.name: '定位页面',
          Strings.locationLocateButton.name: '定位',
          Strings.locationStopLocatingButton.name: '停止定位',
          Strings.locationTime.name: '定位时间: %s',
          Strings.locationLatitude.name: '纬度: %s',
          Strings.locationLongitude.name: '经度: %s',
          Strings.locationAccuracy.name: '精确度: %s',
          Strings.locationCountry.name: '国家: %s',
          Strings.locationProvince.name: '省/州: %s',
          Strings.locationCity.name: '城市: %s',
          Strings.locationCityCode.name: '城市编码: %s',
          Strings.locationDistrict.name: '区域: %s',
          Strings.locationDistrictCode.name: '区域编码: %s',
          Strings.locationStreet.name: '街道: %s',
          Strings.locationStreetNumber.name: '门牌号: %s',
          Strings.locationDescription.name: '详细描述: %s',
          Strings.locationTip.name: '点击「定位」按钮以开始',
          Strings.mapTitle.name: '地图页面',
          Strings.mapTip.name: '如果你已安装高德地图, 点击以导航',
          Strings.mapNormalMap.name: '普通地图',
          Strings.mapSatelliteMap.name: '卫星地图',
          Strings.mapNightMap.name: '夜间地图',
          Strings.mapNavigationMap.name: '导航地图',
          Strings.mapBusMap.name: '公交地图',
          Strings.mapDidNotFindAmap.name: '未检测到高德地图',
        },
      };
}

enum Strings {
  commonOkay,
  commonAlert,
  commonError,
  commonFailToGetInformation,
  commonTip,
  homeTitle,
  homeNavigateToLocationButton,
  homeNavigateToMapButton,
  locationTitle,
  locationLocateButton,
  locationStopLocatingButton,
  locationTime,
  locationLatitude,
  locationLongitude,
  locationAccuracy,
  locationCountry,
  locationProvince,
  locationCity,
  locationCityCode,
  locationDistrict,
  locationDistrictCode,
  locationStreet,
  locationStreetNumber,
  locationDescription,
  locationTip,
  mapTitle,
  mapTip,
  mapNormalMap,
  mapSatelliteMap,
  mapNightMap,
  mapNavigationMap,
  mapBusMap,
  mapDidNotFindAmap,
}
